version: '3'

env:
  VERSION: 0.1.0

tasks:
  build:
    cmds:
      - go build -v http.go

  test:
    deps: [unit, it]

  unit:
    cmds:
      - go test $(go list ./... | grep -v /itests)

  it:
    cmds:
      - go test ./itests/...
